---
- name: List OS versions
  hosts: all
  tasks:
    - name: Show OS details
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
